[changelog]
body = """
## {{ version }} ({{ timestamp | date(format="%Y-%m-%d") }})
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
* {{ commit.message | split(pat="\n") | first | trim }}\
  {% if commit.breaking %} **BREAKING**{% endif %}\
  ({{ commit.id | truncate(length=7, end="") }})\
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactoring" },
  { message = "^docs?", group = "Documentation" },
  { message = "^test", group = "Testing" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore", group = "Miscellaneous" },
  { message = "^ci", skip = true },
  { message = "^build", group = "Build" },
  { message = "^deploy", skip = true },
]
filter_commits = false

[bump]
initial_tag = "0.1.0"
features_always_bump_minor = true
breaking_always_bump_major = true
