name: Run Remote Workflow

on:
  workflow_run:
    workflows: ["Review Dog"]
    types:
      - completed
  # push:
  #   branches:
  #     - main
  # pull_request:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Reuse workflow: Test and lint"
    uses: swibrow/.github/.github/workflows/lint.yml@main