name: Call Terraform Workflow

on:
  push:
  pull_request:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  call-terraform:
    uses: ./.github/workflows/terraform.yaml

