name: Call Terraform Workflow

on:
  pull_request:

jobs:
  call-terraform:
    runs-on: ubuntu-latest
    name: Call Terraform Workflow

    steps:
    - uses: actions/checkout@v4
    - uses: swibrow/.github/.github/workflows/echo.yml@main
      with:
        path: README.md
