name: Call Terraform Workflow

on:
  push:
    branches:
      - main
  # pull_request:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  call-terraform:
    uses: ./.github/workflows/tf-plan-apply.yaml

