name: Test TAG Workflow

on:
  push:

jobs:
  # context:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ github }}
  echo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        foo: [1, 2, 3]
        # bar: []
        # baz: [a, b, c]
    steps:
      - run: echo ${{ matrix.foo }}
      - run: exit 1