name: test pull request sha

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get commit SHA
        run: |
          echo "Commit github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"
          echo "Commit github.sha: ${{ github.sha }}"
          echo "Commit github.event.after: ${{ github.event.after }}"
          echo "Commit github.event.before: ${{ github.event.before }}"
          echo "Commit github.event.before: ${{ github.event.before }}"
          echo "Commit github.event.pull_request.head.repo.default_branch: ${{ github.event.pull_request.head.repo.default_branch }}"
          echo "Commit github.event.pull_request.head.repo.full_name: ${{ github.event.pull_request.head.repo.full_name }}"