name: Test TAG Workflow

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ github }}
  echo:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a PR branch that should be ignored"