name: Test PR branch ignore

on:
  pull_request:
    branches:
      - main
      - '!foo*'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a PR branch that should be ignored"