name: Self-Hosted

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    # runs-on: default
    steps:
    - run: echo "Hello, world! Self hosted runner"
