name: Service B

on:
  push:
    branches: [main]
    paths:
      - "services/service-b/**"
      - "cliff.toml"
      - ".github/workflows/service-b.yaml"
      - ".github/workflows/_release-pipeline.yaml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/_release-pipeline.yaml
    with:
      service_name: service-b
      service_path: services/service-b
