name: Terraform Env Tests

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create Terraform plan
    environment: sandbox
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        env:
          TF_VAR_region: ${{ vars.TF_VAR_FOO}}
        with:
          path: terraform
          label: test
          add_github_comment: false