name: Test Docker Build Push ECR (v3)

on:
  workflow_dispatch:

jobs:
  build:
    uses: DND-IT/github-workflows/.github/workflows/docker-build-push-ecr.yaml@1f36ed2f5988b52ee7365b087ccd562a6277ae66 # v4.1.2
    with:
      environment: test
      aws_account_id: "000000000000"
      aws_region: eu-central-1
      aws_role_name: test-role
      image_name: test-image
      docker_context: .
      docker_push: false
