name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  output:
    runs-on: ubuntu-latest
    name: Output event
    steps:
      - run: echo ${{ toJson(github.event) }}
