on:
  push:

jobs:
  config:
    uses: ./.github/workflows/wf-config.yaml
    # with:
    #   config: ${{ github.event.inputs.config }}

  matrix:
    needs: config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          ${{ fromJson(needs.config.outputs.matrix) }}
    steps:
      - name: Matrix
        run: |
          echo ${{ matrix.environment }}

  get-config:
    needs: config
    runs-on: ubuntu-latest
    steps:
      - name: Get config
        run: |
          echo '${{ needs.config.outputs }}'

  deploy:
    needs: config
    uses: ./.github/workflows/wf-simple.yaml
    with:
      environment: dev