name: Workflow config

on:
  workflow_call:
    inputs:
      config_path:
        required: false
        type: string
        default: .github/config.yaml
      environment:
        description: Pass evnironment name to environment details as outputs
        required: false
        type: string

    outputs:
      config:
        value: ${{ jobs.config.outputs.config }}
      matrix:
        value: ${{ jobs.config.outputs.matrix }}
      environment:
        value: ${{ jobs.config.outputs.environment }}
      aws_account_id:
        value: ${{ jobs.config.outputs.aws_account_id }}
      aws_region:
        value: ${{ jobs.config.outputs.aws_region }}
      aws_role_name:
        value: ${{ jobs.config.outputs.aws_role_name }}

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.config.outputs.config }}
      matrix: ${{ steps.config.outputs.matrix }}
      environment: ${{ steps.config.outputs.environment }}
      aws_account_id: ${{ steps.config.outputs.aws_account_id }}
      aws_region: ${{ steps.config.outputs.aws_region }}
      aws_role_name: ${{ steps.config.outputs.aws_role_name }}

    steps:
      - uses: actions/checkout@v4
      - name: Workflow config
        id: config
        run: |
          if [ ${{ inputs.environment }} ]; then
            aws_account_id=$(yq -o=json '.environment.${{ inputs.environment }}.aws_account_id' ${{ inputs.config_path }})
            aws_region=$(yq -o=json '.environment.${{ inputs.environment }}.aws_region' ${{ inputs.config_path }})
            aws_role_name=$(yq -o=json '.environment.${{ inputs.environment }}.aws_role_name' ${{ inputs.config_path }})

            echo "aws_account_id=$aws_account_id" >> $GITHUB_OUTPUT
            echo "aws_region=$aws_region" >> $GITHUB_OUTPUT
            echo "aws_role_name=$aws_role_name" >> $GITHUB_OUTPUT
          fi

          config=$(yq -o=json '.environment' ${{ inputs.config_path }} | jq -rc)
          matrix=$(yq -o=json '.environment | to_entries | map({"environment": .key} + .value)' ${{ inputs.config_path }} | jq -rc)

          echo "config=$config" >> $GITHUB_OUTPUT
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
