on:
  push:

jobs:
  config:
    uses: ./.github/workflows/wf-config.yaml
    # with:
    #   config_path: ${{ github.event.inputs.config }}

  parallel:
    needs: config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          ${{ fromJson(needs.config.outputs.matrix) }}
    steps:
      - name: Matrix
        run: |
          echo "Deploying ${{ matrix.environment }}"
          echo "Into AWS Account: ${{ matrix.aws_account_id }}"
          echo "Into AWS Region: ${{ matrix.aws_region }}"
          echo "Using AWS Role Name: ${{ matrix.aws_role_name }}"

  single:
    needs: config
    uses: ./.github/workflows/wf-simple.yaml
    with:
      environment: dev

  get-config:
    needs: config
    runs-on: ubuntu-latest
    steps:
      - name: Get config
        run: |
          echo '${{ needs.config.outputs }}'