on:
  workflow_call:
    inputs:
      config_path:
        description: 'Path to config file'
        type: string
        required: false
    outputs:
      environment:
        description: 'Environment name'
        value: ${{ jobs.parallel.outputs.environment }}

run-name: Deploying to all environments by @${{ github.actor }}

jobs:
  matrix-config:
    uses: ./.github/workflows/wf-config.yaml

  parallel:
    needs: matrix-config
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ matrix.environment }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.matrix-config.outputs.matrix) }}
    steps:
      - name: Matrix
        id: matrix
        run: |
          echo "Deploying ${{ matrix.environment }}"
          echo "Into AWS Account: ${{ matrix.aws_account_id }}"
          echo "Into AWS Region: ${{ matrix.aws_region }}"
          echo "Using AWS Role Name: ${{ matrix.aws_role_name }}"
