name: Reuse Artifacts in Cleanup Job

on:
  workflow_run:
    workflows: ["Create Artifacts"]
    types:
      - completed


jobs:
  cleanup:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v5

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: cleanup

      - run: |
          cat ./kube_ns

