name: Run shit

on:
  push:

jobs:
  runshit:
    env:
      stringjson: '"tenant_ingress_prefix": "[\"sanitize-releasename\"]"'
      json: '"tenant_ingress_prefix": ["sanitize-releasename"]'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ fromJson(env.stringjson).tenant_ingress_prefix }}"
      - run: echo "${{ fromJson(env.stringjson).tenant_ingress_prefix[0] }}"
      - run: echo "${{ fromJson(env.json).tenant_ingress_prefix }}"
      - run: echo "${{ fromJson(env.json).tenant_ingress_prefix[0] }}"
      - run: echo "${{ env.json.tenant_ingress_preix }}"
      - run: echo "${{ env.json.tenant_ingress_preix[0] }}"
      - run: echo "${{ toJson(env.stringjson) }}"
      - run: echo "${{ toJson(env.json) }}"

