name: Run shit

on:
  push:

jobs:
  runshit:
    env:
      foo: '"tenant_ingress_prefix": "[\"sanitize-releasename\"]"'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ fromJson(env.foo).tenant_ingress_prefix }}"
      - run: echo "${{ toJson(env.foo) }}"
